spring:
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    h2:
      console:
        enabled: true
    jpa:
      show-sql: true
      properties:
        hibernate.format_sql: true
      hibernate:
        ddl-auto: create

logging:
  level:
    org:
      springframework:
      hibernate:
        type:
          descriptor:
            sql: trace